server:
  port: 9093

eureka:
  client:
    service-url:
      defaultZone: ${eureka_url}

spring:
  application:
    name: ORDER-SERVICE
  data:
    mongodb:
      uri: ${db_url}
      host: localhost
      port: 27017
      database: orderdb
      repositories:
        enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

logging:
  level:
    root: INFO
    com.shikbetumio.order: DEBUG
    org.springframework.web: ERROR
